# -*- coding: utf-8 -*-
"""ipl_data_analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RKhqAFs7UjSaJbWMF4p7S5yXyXe28RrY
"""

pip install pandas matplotlib seaborn

# ==========================================
# IPL DATA ANALYTICS PROJECT
# ==========================================

# Import Libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

# ------------------------------------------
# Create folders
# ------------------------------------------

os.makedirs("charts", exist_ok=True)
os.makedirs("output", exist_ok=True)

# ------------------------------------------
# Load Datasets
# ------------------------------------------

matches = pd.read_csv("matches.csv")
deliveries = pd.read_csv("deliveries.csv")

# ------------------------------------------
# Display Dataset Information
# ------------------------------------------

print("\n========== MATCHES DATA ==========\n")
print(matches.head())

print("\n========== DELIVERIES DATA ==========\n")
print(deliveries.head())

# ------------------------------------------
# Save cleaned datasets
# ------------------------------------------

matches.to_csv("output/cleaned_matches.csv", index=False)
deliveries.to_csv("output/cleaned_deliveries.csv", index=False)

print("\n✅ Cleaned datasets saved!")

# ==========================================
# 1. MOST SUCCESSFUL IPL TEAMS
# ==========================================

team_wins = matches['winner'].value_counts()

plt.figure(figsize=(12,6))

sns.barplot(
    x=team_wins.index,
    y=team_wins.values
)

plt.xticks(rotation=75)

plt.title("Most Successful IPL Teams")
plt.xlabel("Teams")
plt.ylabel("Wins")

plt.savefig("charts/team_wins.png")

plt.show()

print("✅ team_wins.png saved!")

# ==========================================
# 2. TOP RUN SCORERS
# ==========================================

top_batsmen = deliveries.groupby('batter')['batsman_runs'].sum().sort_values(ascending=False).head(10)

plt.figure(figsize=(12,6))

sns.barplot(
    x=top_batsmen.index,
    y=top_batsmen.values
)

plt.xticks(rotation=45)

plt.title("Top 10 IPL Run Scorers")
plt.xlabel("Player")
plt.ylabel("Runs")

plt.savefig("charts/top_batsmen.png")

plt.show()

print("✅ top_batsmen.png saved!")

# ==========================================
# 3. MOST SIXES
# ==========================================

sixes = deliveries[deliveries['batsman_runs'] == 6]

top_six_hitters = sixes['batter'].value_counts().head(10)

plt.figure(figsize=(12,6))

sns.barplot(
    x=top_six_hitters.index,
    y=top_six_hitters.values
)

plt.xticks(rotation=45)

plt.title("Top 10 Six Hitters")
plt.xlabel("Player")
plt.ylabel("Number of Sixes")

plt.savefig("charts/top_six_hitters.png")

plt.show()

print("✅ top_six_hitters.png saved!")

# ==========================================
# 4. TOSS DECISION ANALYSIS
# ==========================================

toss_decision = matches['toss_decision'].value_counts()

plt.figure(figsize=(6,6))

plt.pie(
    toss_decision.values,
    labels=toss_decision.index,
    autopct='%1.1f%%'
)

plt.title("Toss Decision Analysis")

plt.savefig("charts/toss_decision.png")

plt.show()

print("✅ toss_decision.png saved!")

# ==========================================
# 5. MATCHES PER SEASON
# ==========================================

matches_per_season = matches['season'].value_counts().sort_index()

plt.figure(figsize=(12,6))

matches_per_season.plot(marker='o')

plt.title("IPL Matches Per Season")
plt.xlabel("Season")
plt.ylabel("Matches")

plt.savefig("charts/matches_per_season.png")

plt.show()

print("✅ matches_per_season.png saved!")

# ==========================================
# FINAL INSIGHTS
# ==========================================

print("\n========== IPL ANALYTICS INSIGHTS ==========\n")

print("1. Mumbai Indians and Chennai Super Kings are among the most successful teams.")
print("2. Virat Kohli and top players dominate run charts.")
print("3. Aggressive batsmen dominate six-hitting statistics.")
print("4. Teams prefer fielding after winning the toss.")
print("5. IPL popularity increased across seasons.")

print("\n========== PROJECT COMPLETED SUCCESSFULLY ==========\n")